#############################################################################
# Makefile for building: Poolgame.app/Contents/MacOS/Poolgame
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  Poolgame.pro
# Template: app
# Command: /Users/dengxing/Qt5.9.4/5.9.4/clang_64/bin/qmake -o Makefile Poolgame.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers -I../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers -I../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang -F/Users/dengxing/Qt5.9.4/5.9.4/clang_64/lib
QMAKE         = /Users/dengxing/Qt5.9.4/5.9.4/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/dengxing/Qt5.9.4/5.9.4/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/dengxing/Qt5.9.4/5.9.4/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Poolgame1.0.0
DISTDIR = /Users/dengxing/Desktop/Poolgame/.tmp/Poolgame1.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wl,-rpath,@executable_path/Frameworks -Wl,-rpath,/Users/dengxing/Qt5.9.4/5.9.4/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/dengxing/Qt5.9.4/5.9.4/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dialog.cpp \
		stageonefactory.cpp \
		ball.cpp \
		table.cpp \
		game.cpp \
		gamebuilder.cpp \
		stagetwofactory.cpp \
		pocket.cpp \
		stagetwobuilder.cpp \
		balldecorator.cpp moc_dialog.cpp
OBJECTS       = main.o \
		dialog.o \
		stageonefactory.o \
		ball.o \
		table.o \
		game.o \
		gamebuilder.o \
		stagetwofactory.o \
		pocket.o \
		stagetwobuilder.o \
		balldecorator.o \
		moc_dialog.o
DIST          = config.json \
		config.json \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/qdevice.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/unix.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/macx.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/qconfig.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resources.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/moc.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/uic.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/lex.prf \
		Poolgame.pro dialog.h \
		abstractstagefactory.h \
		stageonefactory.h \
		ball.h \
		table.h \
		game.h \
		gamebuilder.h \
		utils.h \
		stagetwofactory.h \
		pocket.h \
		stagetwobuilder.h \
		balldecorator.h \
		mouseeventable.h main.cpp \
		dialog.cpp \
		stageonefactory.cpp \
		ball.cpp \
		table.cpp \
		game.cpp \
		gamebuilder.cpp \
		stagetwofactory.cpp \
		pocket.cpp \
		stagetwobuilder.cpp \
		balldecorator.cpp
QMAKE_TARGET  = Poolgame
DESTDIR       = 
TARGET        = Poolgame.app/Contents/MacOS/Poolgame

####### Custom Variables
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_VALID_ARCHS = x86_64
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

$(TARGET): ui_dialog.h $(OBJECTS)  
	@test -d Poolgame.app/Contents/MacOS/ || mkdir -p Poolgame.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Poolgame.pro ../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/qdevice.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/unix.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/macx.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/sanitize.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/qconfig.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/toolchain.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resources.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/moc.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/uic.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qmake_use.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/file_copies.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/lex.prf \
		Poolgame.pro \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile Poolgame.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/qdevice.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/device_config.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/unix.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/mac.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/macx.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/sanitize.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/qconfig.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_cgl_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/spec_post.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/toolchain.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/default_post.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qml_debug.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qt.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/resources.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/moc.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/uic.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/qmake_use.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/file_copies.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/yacc.prf:
../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/lex.prf:
Poolgame.pro:
../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Poolgame.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

Poolgame.app/Contents/PkgInfo: 
	@test -d Poolgame.app/Contents || mkdir -p Poolgame.app/Contents
	@$(DEL_FILE) Poolgame.app/Contents/PkgInfo
	@echo "APPL????" > Poolgame.app/Contents/PkgInfo
Poolgame.app/Contents/Resources/empty.lproj: 
	@test -d Poolgame.app/Contents/Resources || mkdir -p Poolgame.app/Contents/Resources
	@touch Poolgame.app/Contents/Resources/empty.lproj
	
Poolgame.app/Contents/Info.plist: 
	@test -d Poolgame.app/Contents || mkdir -p Poolgame.app/Contents
	@$(DEL_FILE) Poolgame.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,xden2331.Poolgame,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,Poolgame,g" -e "s,@LIBRARY@,Poolgame,g" -e "s,@TYPEINFO@,????,g" ../../Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang/Info.plist.app >Poolgame.app/Contents/Info.plist

all: Makefile \
		Poolgame.app/Contents/PkgInfo \
		Poolgame.app/Contents/Resources/empty.lproj \
		Poolgame.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dialog.h abstractstagefactory.h stageonefactory.h ball.h table.h game.h gamebuilder.h utils.h stagetwofactory.h pocket.h stagetwobuilder.h balldecorator.h mouseeventable.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp dialog.cpp stageonefactory.cpp ball.cpp table.cpp game.cpp gamebuilder.cpp stagetwofactory.cpp pocket.cpp stagetwobuilder.cpp balldecorator.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r Poolgame.app
	-$(DEL_FILE) Makefile


####### Sub-libraries

first: all copyconfig

copyconfig: ../Poolgame/config.json
	$(COPY_FILE) "/Users/dengxing/Desktop/Poolgame/config.json" .

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.10 -Wall -W -dM -E -o moc_predefs.h ../../Qt5.9.4/5.9.4/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp
moc_dialog.cpp: ../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		game.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		abstractstagefactory.h \
		table.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		balldecorator.h \
		utils.h \
		mouseeventable.h \
		dialog.h \
		moc_predefs.h \
		../../Qt5.9.4/5.9.4/clang_64/bin/moc
	/Users/dengxing/Qt5.9.4/5.9.4/clang_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/Users/dengxing/Qt5.9.4/5.9.4/clang_64/mkspecs/macx-clang -I/Users/dengxing/Desktop/Poolgame -I/Users/dengxing/Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers -I/Users/dengxing/Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers -I/Users/dengxing/Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/9.1.0/include -I/Library/Developer/CommandLineTools/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.13.sdk/usr/include -F/Users/dengxing/Qt5.9.4/5.9.4/clang_64/lib dialog.h -o moc_dialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h
ui_dialog.h: dialog.ui \
		../../Qt5.9.4/5.9.4/clang_64/bin/uic
	/Users/dengxing/Qt5.9.4/5.9.4/clang_64/bin/uic dialog.ui -o ui_dialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp dialog.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		game.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		abstractstagefactory.h \
		table.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		balldecorator.h \
		utils.h \
		mouseeventable.h \
		gamebuilder.h \
		stageonefactory.h \
		stagetwofactory.h \
		stagetwobuilder.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QFile \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsondocument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dialog.o: dialog.cpp dialog.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		game.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		abstractstagefactory.h \
		table.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		balldecorator.h \
		utils.h \
		mouseeventable.h \
		ui_dialog.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cpp

stageonefactory.o: stageonefactory.cpp stageonefactory.h \
		abstractstagefactory.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		table.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stageonefactory.o stageonefactory.cpp

ball.o: ball.cpp ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ball.o ball.cpp

table.o: table.cpp table.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o table.o table.cpp

game.o: game.cpp game.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		abstractstagefactory.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		table.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		balldecorator.h \
		utils.h \
		mouseeventable.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonarray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

gamebuilder.o: gamebuilder.cpp gamebuilder.h \
		stageonefactory.h \
		abstractstagefactory.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		table.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		stagetwofactory.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		game.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		balldecorator.h \
		utils.h \
		mouseeventable.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonarray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gamebuilder.o gamebuilder.cpp

stagetwofactory.o: stagetwofactory.cpp stagetwofactory.h \
		abstractstagefactory.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		table.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stagetwofactory.o stagetwofactory.cpp

pocket.o: pocket.cpp pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pocket.o pocket.cpp

stagetwobuilder.o: stagetwobuilder.cpp stagetwobuilder.h \
		gamebuilder.h \
		stageonefactory.h \
		abstractstagefactory.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		table.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		pocket.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		stagetwofactory.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		game.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		balldecorator.h \
		utils.h \
		mouseeventable.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qjsonarray.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stagetwobuilder.o stagetwobuilder.cpp

balldecorator.o: balldecorator.cpp balldecorator.h \
		ball.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/QPoint \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QVector2D \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qvector2d.h \
		utils.h \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/QMouseEvent \
		../../Qt5.9.4/5.9.4/clang_64/lib/QtGui.framework/Headers/qevent.h \
		mouseeventable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o balldecorator.o balldecorator.cpp

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

